all:
  children:
    local:
      hosts:
        localhost:
          user: "{{ lookup('env', 'USER') }}"
          home: "{{ lookup('env', 'HOME') }}"
    ubuntu:
      hosts:
        192.168.0.191:
          user: "{{ lookup('env', 'USER') }}"
          home: "{{ lookup('env', 'HOME') }}"
