all:
  children:
    mac:
      hosts:
        Joshs-MacBook-Pro:
          user: bbraunj
          group: staff
        jarvis:
          user: bbraunj
          group: staff
    local:
      hosts:
        localhost:
          tasks:
            - name: Get group name
              command: id -gn $USER
              register: usergroup

          user: "{{ lookup('env', 'USER') }}"
          group: "{{ usergroup.stdout }}"
