all:
  children:
    mac:
      hosts:
        Joshs-MacBook-Pro:
          user: bbraunj
          group: staff
        jarvis:
          user: bbraunj
          group: staff
    local:
      hosts:
        localhost:
          user: "{{ lookup('env', 'USER') }}"
