---

- hosts: localhost
  connection: local
  become: no

  roles:
    - role: base
      tags:
        - base
    - role: workstation
      tags:
        - workstation

# - hosts: ubuntu
#   connection: ssh
#   become: no
# 
#   roles:
#     - role: base
#       tags:
#         - base
#     - role: workstation
#       tags:
#         - workstation
