- name: Scripts
  tags:
  - scripts

  block:
  - name: Copy scripts
    ansible.builtin.copy:
      src: .scripts
      dest: "{{ home }}/"
      owner: "{{ user }}"

  - name: Copy tex templates
    ansible.builtin.copy:
      src: .templates
      dest: "{{ home }}/"
      owner: "{{ user }}"
      backup: yes
