- name: Install scipy packages + numba
  pip:
    name: numpy, scipy, matplotlib, ipython, jupyter, pandas, sympy, nose, numba

- name: Install flake8
  pip:
    name: flake8

- name: Install neovim Python package
  pip:
    name: neovim

- name: Install pudb
  pip:
    name: pudb

- name: Install pytest and pytest-cov
  pip:
    name: pytest, pytest-cov

- name: Install sphinx and related packages
  pip:
    name: sphinx, sphinx-argparse, sphinx-rtd-theme
