- block:
  - name: Install ansible-galaxy requirements
    command: ansible-galaxy install -r roles/base/requirements.yml

  - import_tasks: software/homebrew.yml
  - import_tasks: software/python.yml
