- name: Dotfiles
  tags:
  - preferences
  - dotfiles

  block:
  - name: Copy .vimrc
    ansible.builtin.copy:
      src: .vimrc
      dest: "/Users/{{ user }}/.vimrc"
      owner: "{{ user }}"
      group: "{{ group }}"
