- name: App Preferences
  tags:
    - app_preferences
    - MacOSX

  block:
  - name: Copy Alfred Preferences
    when:
      ansible_distribution == "MacOSX"
    ansible.builtin.copy:
      src: Alfred.alfredpreferences
      dest: "/Users/{{ user }}/Library/Application Support/Alfred/"
      owner: "{{ user }}"
